---
title: "reshape incalss"
author: "Christine"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
```

Let's put this up to github

```{r}
gdp <- read_delim("../../data/oecd-gdp.csv.bz2")
gdp
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator))
gdpLong %>% 
  head(10)
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator),
               names_to = "year",
               values_to = "gdp")
gdpLong %>% 
  head(10)
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator),
               names_to = "year",
               values_to = "gdp") %>% 
  mutate(year = as.numeric(year))
gdpLong %>% 
  head(10)
```

```{r}
p <- data.frame(pregnant = c("Yes", "No"),
            	male = c(NA, 25),
            	female = c(11, 18))
p
```

```{r}
pl <- p %>%
  pivot_longer(c(male, female),
           	names_to = "sex",
           	values_to = "count")
pl
```

```{r}
pl %>%
  pivot_wider(id_cols = pregnant,
          	names_from = sex,
          	values_from = count)
```

